name: WeaponsAPI
main: com.github.robotnikthingy.weaponsapi.WeaponsAPIPlugin
version: 1.0.0
author: Robotnikman (and anyone else who contributes, add your name here)
load: startup
description: Used to create and manage weapons of all types
website:
commands:
  worldschematics:
    description: The main WorldSchematics Command
    permission: worldschematics.admin
permissions:
  worldschematics.*:
    description: Gives access to all WorldSchematics commands
    children:
      worldschematics.admin: true
  worldschematics.admin:
    description: Allows you to use WorldSchematics Admin commands
    default: op

depend: [WorldEdit]
softdepend: [MythicMobs, CrackShot]